### PR TITLE
Ant build file and a sample skeleton

### PR DESCRIPTION
**Pull request by pnewhook**
I have an ant build file that works with a pretty handy, if basic, app skeleton. I have a readme that begins explaining how to do things. The ant file works directly against the deploy jar instead of the batch file because calling batch from ant is a pain and not cross platform.
Speaking of cross-platform, you'll wan to look at the call to bbwp.exe, and make it run properly on a Mac. I don't have access to a Mac.
I've also included a branch from Muerl which includes a tidy little batch file.
I expect you'll want to look at this any maybe pull it apart a bit. Please let me know if you have any questions.

### CODE REVIEW

**Comment by tneil** [comment]
Hi pnewhook,

Thanks for the contribution!  We have a bunch of work we are doing right now around our build systems that we are looking to push up into the community.  We are making sure that everything will run on your desktop with an integrated unit testing framework utilizing public open frameworks.

I'll definitely pass the pull request on to the team to see if there are parts that we could incorporate into the build work we have underway.  

As a bit of background, right now most of our build script work is using Maven

**Comment by tneil** [comment]
Hi pnewhook,

I've added some comments to your issue thread that should "pull" some of these ideas together. That was a really bad pun but I couldn't resist :)

https://github.com/blackberry/WebWorks-TabletOS/issues/#issue/1

We also have a thread going on in the WebWorks for Smartphones repository that will bring some further context.

https://github.com/blackberry/WebWorks/issues#issue/3

**Comment by pnewhook** [comment]
Thanks Tim, but just to be clear, my ant file builds and deploys an **app**  to the simulator. I never intended to use it to build the sdk.

**Comment by tneil** [comment]
Ahhhhh... ok I thought it was an SDK build script... I'll have the team take a look into it

**Comment by pelegri** [comment]
Is this one still a valid request?  If not, can we close it?

**Comment by pnewhook** [comment]
Nope, this fell out of usefulness long ago.

**Pull request closed without merging**
